<?php
$server='localhost';
$user="root";
$password="";
$DataBase="AvtoServis";
$connection=mysqli_connect("$server","$user","$password","$DataBase");
if(!$connection)
{
    die("Xatolik".mysqli_connect_error());
}
?>