<?php
$server='localhost';
$user="root";
$password="";
$DataBase="AvtoServis";
$conn=mysqli_connect("$server","$user","$password","$DataBase");
if(!$conn)
{
    die("Xatolik".mysqli_connect_error());
}
?>